# Generated by Django 2.1.4 on 2018-12-11 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20181211_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='modified_date',
            field=models.DateTimeField(),
        ),
    ]
