# Generated by Django 2.1.4 on 2018-12-14 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_thumb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='article',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='article',
            name='thumb',
        ),
    ]
