# Generated by Django 2.1.4 on 2018-12-14 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20181214_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='archive',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='articles.Archive'),
        ),
    ]
