# Generated by Django 2.1.4 on 2018-12-15 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_article_excerpt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='excerpt',
        ),
    ]
